### PR TITLE
Add nmcli (NetworkManager CLI) wrapper on Linux

### PR DESCRIPTION
**Pull request by monkbroc**
Add support for scanning wifi network without root using NetworkManager

NetworkManager is the standard Linux network configuration tool suite used on Fedora, Debian, Ubuntu, Gentoo, CentOS or openSUSE

This is needed because iwlist needs sudo to be able to scan wifi networks

### CODE REVIEW

**Comment by brycekahle** [comment]
Can you add your parsing terms to `locales/en.json` and use them in your parsing function? This will make it easier to add other locale support in the future.

**Comment by monkbroc** [comment]
No locale necessary. `nmcli --terse` always outputs in English using easily
parseable formats.

**Comment by brycekahle** [comment]
Ok. Would you mind adding a test or two?

**Comment by monkbroc** [comment]
Sure

**Comment by monkbroc** [comment]
It turns out I was wrong about `--terse` always using English so I added a locale section for `nmcli`.

**Comment by brycekahle** [comment]
Rawk.

**Pull request merged**
